version: '3.8'

services:
  weapon-generator:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./generated_weapons:/app/generated_weapons
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    
  # Optional: Redis for job queue in production
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: